-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 22:53:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema culampollamydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema culampollamydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `culampollamydb` DEFAULT CHARACTER SET utf8 ;
USE `culampollamydb` ;

-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_pais` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_pais` (
  `idtb_pais` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NULL,
  `cod_iso2` VARCHAR(2) NULL,
  `cod_iso3` VARCHAR(3) NULL,
  PRIMARY KEY (`idtb_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_provincia` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_provincia` (
  `idtb_provincia` INT NOT NULL AUTO_INCREMENT,
  `codprovincia` VARCHAR(45) NULL,
  `nomprovincia` VARCHAR(45) NULL,
  `pais_id` INT NULL,
  PRIMARY KEY (`idtb_provincia`),
  INDEX `fk_provincia_pais_id_idx` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_provincia_pais_id`
    FOREIGN KEY (`pais_id`)
    REFERENCES `culampollamydb`.`tb_pais` (`idtb_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_codigopostal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_codigopostal` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_codigopostal` (
  `idtb_codigopostal` INT NOT NULL AUTO_INCREMENT,
  `codigopostal` VARCHAR(45) NULL,
  `poblacion` VARCHAR(45) NULL,
  `provincia_id` INT NULL,
  `pais_id` INT NULL,
  PRIMARY KEY (`idtb_codigopostal`),
  INDEX `fk_codpostal_provincia_id_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_codpostal_pais_id_idx` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_codpostal_provincia_id`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `culampollamydb`.`tb_provincia` (`idtb_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codpostal_pais_id`
    FOREIGN KEY (`pais_id`)
    REFERENCES `culampollamydb`.`tb_pais` (`idtb_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_proveedores` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_proveedores` (
  `idproveedores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `nif` INT(9) UNSIGNED NULL,
  `direccion` VARCHAR(150) NULL,
  `ciudad` VARCHAR(45) NULL,
  `codigopostal_id` INT NULL,
  `pais_id` INT NULL,
  PRIMARY KEY (`idproveedores`),
  INDEX `fk_proveedor_codpostal_id_idx` (`codigopostal_id` ASC) VISIBLE,
  INDEX `fk_proveedor_pais_id_idx` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_codpostal_id`
    FOREIGN KEY (`codigopostal_id`)
    REFERENCES `culampollamydb`.`tb_codigopostal` (`idtb_codigopostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_pais_id`
    FOREIGN KEY (`pais_id`)
    REFERENCES `culampollamydb`.`tb_pais` (`idtb_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_clientes` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(150) NULL,
  `direccion` VARCHAR(45) NULL,
  `codigopostal_id` INT NULL,
  `telefono` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  `fecha_registro` DATE NULL,
  PRIMARY KEY (`id_clientes`),
  INDEX `fk_cliente_codpostal_id_idx` (`codigopostal_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_codpostal_id`
    FOREIGN KEY (`codigopostal_id`)
    REFERENCES `culampollamydb`.`tb_codigopostal` (`idtb_codigopostal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_marca` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nombremarca` VARCHAR(45) NULL,
  `proveedor_id` INT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `fkproveedor_idx` (`proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_marca_proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `culampollamydb`.`tb_proveedores` (`idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_recomendados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_recomendados` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_recomendados` (
  `id_cliente` INT NOT NULL,
  `id_recomendado` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `id_recomendado`),
  INDEX `id_recomendado_idx_idx` (`id_recomendado` ASC) VISIBLE,
  CONSTRAINT `id_recomendado_cliente_reco`
    FOREIGN KEY (`id_recomendado`)
    REFERENCES `culampollamydb`.`tb_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_recomendado_cliente_orig`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `culampollamydb`.`tb_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_tipomontura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_tipomontura` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_tipomontura` (
  `id_tipo_montura` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_montura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_gafas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_gafas` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_gafas` (
  `id_tipogafas` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NULL,
  `marca_id` INT NULL,
  `tipo_montura_id` INT NULL,
  `color` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  INDEX `fkproveedor_idx` (`marca_id` ASC) INVISIBLE,
  INDEX `fktipomontura_idx` (`tipo_montura_id` ASC) VISIBLE,
  PRIMARY KEY (`id_tipogafas`),
  CONSTRAINT `fk_gafas_marca_id`
    FOREIGN KEY (`marca_id`)
    REFERENCES `culampollamydb`.`tb_marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gafas_tipomontura_id`
    FOREIGN KEY (`tipo_montura_id`)
    REFERENCES `culampollamydb`.`tb_tipomontura` (`id_tipo_montura`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_empleado` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `apellidos` VARCHAR(100) NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_colorvidrio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_colorvidrio` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_colorvidrio` (
  `id_colorvidrio` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id_colorvidrio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `culampollamydb`.`tb_gafasvendidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `culampollamydb`.`tb_gafasvendidas` ;

CREATE TABLE IF NOT EXISTS `culampollamydb`.`tb_gafasvendidas` (
  `id_gafasvendidas` INT NOT NULL AUTO_INCREMENT,
  `tipogafas_id` INT NULL,
  `gradvidrio_izq` FLOAT NULL,
  `gradvidrio_der` FLOAT NULL,
  `colorvidrio_izq` INT NULL DEFAULT 1,
  `colorvidrio_der` INT NULL DEFAULT 1,
  `empleado_id` INT NULL,
  `cliente_id` INT NULL,
  INDEX `ermpleado_idx_idx` (`empleado_id` ASC) VISIBLE,
  INDEX `cliente_idx_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `tipogafas_idx_idx` (`tipogafas_id` ASC) VISIBLE,
  PRIMARY KEY (`id_gafasvendidas`),
  INDEX `colorVidrioizq_idx` (`colorvidrio_izq` ASC) VISIBLE,
  INDEX `colorVidrioder_idx` (`colorvidrio_der` ASC) VISIBLE,
  CONSTRAINT `empleado_idx`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `culampollamydb`.`tb_empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente_idx`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `culampollamydb`.`tb_clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tipogafas_idx`
    FOREIGN KEY (`tipogafas_id`)
    REFERENCES `culampollamydb`.`tb_gafas` (`id_tipogafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colorVidrioizq`
    FOREIGN KEY (`colorvidrio_izq`)
    REFERENCES `culampollamydb`.`tb_colorvidrio` (`id_colorvidrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `colorVidrioder`
    FOREIGN KEY (`colorvidrio_der`)
    REFERENCES `culampollamydb`.`tb_colorvidrio` (`id_colorvidrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
